package uk.ac.ebi.spot.gwas.deposition.audit.constants;

public enum PublicationEventType {


    SUBMISSION_CREATED,
    TEMPLATE_UPLOAD,
    CURATION_STATUS_UPDATED,
    CURATOR_UPDATED,
    PMID_CREATED,
    PMID_ADDED,
    SUBMISSION_UPDATE,
    TRAIT_UPDATED,
    SAMPLE_UPDATED,
    SNP_APPROVED,
    IMPORTED,
    MAPPING_COMPLETE,
    SS_VALIDATION_FAILED,
    SS_VALIDATION_SUCCESS,
    METADATA_VALIDATION_FAILED,
    METADATA_VALIDATION_SUCCESS;


}
